name: MAKE CHANGE DAILY
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75833
title: "Daily actions are the easiest way to create lasting change, for yourself & for others. Here's my journey."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9103638909291476
  lightness: 0.9352269084192812
  saturation: 0.6465635425411165
  rhythmicContrast: 0.8638636218383908
purpose: []
